security:
    encoders:
        App\Infrastructure\Security\SecurityUser:
            algorithm: argon2i
    providers:
        user_provider:
            id: App\Infrastructure\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: user_provider
            pattern: ^/
            logout:
                path: logout
            guard:
                authenticators:
                    - App\Infrastructure\Security\WebAuthenticator
