home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: home.html.twig

registration:
  path: /registration
  controller: App\UserInterface\Controller\RegistrationController