coming_soon:
  path: /coming-soon
  methods: [GET,POST,PUT]
  controller: App\Controller\ComingSoonSubscribeController
  
app_home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /coming-soon
    permanent: false